### ISSUE TITLE
Runtime Error on Build

### ISSUE THREAD

**Issue by sumitpathak6** [said7388/developer-portfolio#22]
Facing an unhandled runtime build error
Error: States missing required paramters: sitekey

Here  is the npm run dev build log :
⨯ node_modules\lottie-web\build\player\lottie.js (30:0) @ createTag
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (C:\Users\Office\OneDrive\Desktop\developer-portfolio\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\Office\OneDrive\Desktop\developer-portfolio\.next\server\webpack-runtime.js:33:43)
    at eval (./app/components/helper/animation-lottie.jsx:7:70)
    at (ssr)/./app/components/helper/animation-lottie.jsx (C:\Users\Office\OneDrive\Desktop\developer-portfolio\.next\server\app\page.js:272:1)
    at __webpack_require__ (C:\Users\Office\OneDrive\Desktop\developer-portfolio\.next\server\webpack-runtime.js:33:43)
    
    
    
    Would require an urgent faceoff for this issue please.

**Comment by said7388** [comment]
This error is for the reCaptcha key.  I will make it optional. Please wait while I make the necessary changes.

**Comment by sumitpathak6** [comment]
Is it done?
